import Expense, {Category} from '../model/Expenses';

export const expenses: Expense[] = [
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 1,
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 2,
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Concert',
        id: 3,
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: new Date(),
        description: 'Dinner',
        id: 4,
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Taxi fare',
        id: 5,
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Movie',
        id: 6,
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 7,
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 8,
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Concert',
        id: 9,
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: new Date(),
        description: 'Dinner',
        id: 10,
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Taxi fare',
        id: 11,
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Movie',
        id: 12,
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 13,
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 14,
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Concert',
        id: 15,
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: new Date(),
        description: 'Dinner',
        id: 16,
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Taxi fare',
        id: 17,
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Movie',
        id: 18,
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 19,
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 20,
    },
];
