import Expense, { Category } from '../model/Expenses';

export const ExpenseList: Expense[] = [
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 1,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 2,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Concert',
        id: 3,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: new Date(),
        description: 'Dinner',
        id: 4,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Taxi fare',
        id: 5,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Movie',
        id: 6,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 7,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 8,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Concert',
        id: 9,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: new Date(),
        description: 'Dinner',
        id: 10,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Taxi fare',
        id: 11,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Movie',
        id: 12,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 13,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 14,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Concert',
        id: 15,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: new Date(),
        description: 'Dinner',
        id: 16,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Taxi fare',
        id: 17,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: new Date(),
        description: 'Movie',
        id: 18,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: new Date(),
        description: 'Lunch',
        id: 19,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: new Date(),
        description: 'Bus fare',
        id: 20,
        account: 'Cash',
        receiver: 'McDonalds',
    },
];
