/*
const calcDate = () => {
    let yourDate = new Date();
    yourDate.toISOString().split('T')[0];
    const offset = yourDate.getTimezoneOffset();
    yourDate = new Date(yourDate.getTime() - offset * 60 * 1000);
    return yourDate.toISOString().split('T')[0];
};

export const ExpenseList: Expense[] = [
    {
        category: Category.FOOD,
        amount: 20,
        date: calcDate(),
        description: 'Lunch',
        id: 1,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: calcDate(),
        description: 'Bus fare',
        id: 2,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: calcDate(),
        description: 'Concert',
        id: 3,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: calcDate(),
        description: 'Dinner',
        id: 4,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: calcDate(),
        description: 'Taxi fare',
        id: 5,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: calcDate(),
        description: 'Movie',
        id: 6,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: calcDate(),
        description: 'Lunch',
        id: 7,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: calcDate(),
        description: 'Bus fare',
        id: 8,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: calcDate(),
        description: 'Concert',
        id: 9,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: calcDate(),
        description: 'Dinner',
        id: 10,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: calcDate(),
        description: 'Taxi fare',
        id: 11,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: calcDate(),
        description: 'Movie',
        id: 12,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: calcDate(),
        description: 'Lunch',
        id: 13,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: calcDate(),
        description: 'Bus fare',
        id: 14,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: calcDate(),
        description: 'Concert',
        id: 15,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 30,
        date: calcDate(),
        description: 'Dinner',
        id: 16,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: calcDate(),
        description: 'Taxi fare',
        id: 17,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.ENTERTAIMENT,
        amount: 100,
        date: calcDate(),
        description: 'Movie',
        id: 18,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.FOOD,
        amount: 20,
        date: calcDate(),
        description: 'Lunch',
        id: 19,
        account: 'Cash',
        receiver: 'McDonalds',
    },
    {
        category: Category.TRANSPORTATION,
        amount: 10,
        date: calcDate(),
        description: 'Bus fare',
        id: 20,
        account: 'Cash',
        receiver: 'McDonalds',
    },
];
*/
